# Generated by Django 4.2.x
#
# No schema changes. This migration exists only to document that
# CollegeSettings media fields are now expected to be managed via
# Django FileField mechanisms (admin/CLI).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_unify_college_settings'),
    ]

    operations = []
