# Generated by Django 4.2.25 on 2025-10-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.level')),
                ('current_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.session')),
                ('entry_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_students', to='students.level')),
            ],
        ),
    ]
