# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Session when student first enrolled',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='entry_students',
                to='students.session',
            ),
        ),
    ]
