# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_entry_session_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, null=True, unique=True, max_length=254, help_text="Student's email address"),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, null=True, max_length=15, help_text="Student's phone number"),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, help_text="Student's date of birth"),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=10,
                choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')],
            ),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, help_text='Home address'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, null=True, max_length=100, help_text='Emergency contact person'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, null=True, max_length=15, help_text='Emergency contact phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(auto_now_add=True, help_text='Date student was admitted'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, help_text='Date student graduated'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(
                max_length=20,
                default='active',
                help_text='Current academic status',
                choices=[
                    ('active', 'Active'),
                    ('suspended', 'Suspended'),
                    ('graduated', 'Graduated'),
                    ('dropped', 'Dropped Out'),
                    ('transferred', 'Transferred'),
                    ('deferred', 'Deferred'),
                    ('expelled', 'Expelled'),
                ],
            ),
        ),
        migrations.AddField(
            model_name='student',
            name='current_cgpa',
            field=models.FloatField(default=0.0, help_text='Current Cumulative Grade Point Average'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_units_attempted',
            field=models.PositiveIntegerField(default=0, help_text='Total units attempted'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_units_passed',
            field=models.PositiveIntegerField(default=0, help_text='Total units passed'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_sessions_completed',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed sessions'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, null=True, default='Nigerian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='state_of_origin',
            field=models.CharField(blank=True, null=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='local_government',
            field=models.CharField(blank=True, null=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, null=True, max_length=50, help_text='Relationship to emergency contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_email',
            field=models.EmailField(blank=True, null=True, max_length=254, help_text='Emergency contact email'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_scholarship_recipient',
            field=models.BooleanField(default=False, help_text='Student is on scholarship'),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.TextField(blank=True, null=True, help_text='Special accommodation needs'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, help_text='Internal notes about student'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(
                check=models.Q(('current_cgpa__gte', 0.0), ('current_cgpa__lte', 4.0)),
                name='valid_cgpa_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(
                check=models.Q(('total_units_passed__lte', models.F('total_units_attempted'))),
                name='passed_units_not_exceed_attempted',
            ),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_stu_student_0bbbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_stu_email_5a6008_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_level', 'status'], name='students_stu_current_7050b2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['entry_session'], name='students_stu_entry_s_1c1dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_stu_status_4d56ea_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_date'], name='students_stu_admissi_9d2b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_cgpa'], name='students_stu_current_5c4d44_idx'),
        ),
    ]
