# Generated by Django 4.2.25 on 2026-01-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_expand_student_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_student_e7126a_idx',
            old_name='students_stu_student_0bbbd8_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_email_e271bc_idx',
            old_name='students_stu_email_5a6008_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_current_30898d_idx',
            old_name='students_stu_current_7050b2_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_entry_s_98a035_idx',
            old_name='students_stu_entry_s_1c1dd8_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_status_5e2210_idx',
            old_name='students_stu_status_4d56ea_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_admissi_4d51f0_idx',
            old_name='students_stu_admissi_9d2b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_current_c52687_idx',
            old_name='students_stu_current_5c4d44_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text="Student's photograph", null=True, upload_to='students/photos/'),
        ),
    ]
