# Generated by Django 4.2.25 on 2026-01-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_student_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark as the current active session'),
        ),
    ]
