# Generated by Django 4.2.25 on 2026-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_session_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='is_active',
            new_name='is_current',
        ),
        migrations.AlterField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Mark as the current session'),
        ),
    ]
