# Generated by Django 4.2.25 on 2025-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='college_signatures/')),
                ('letterhead', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'College Settings',
            },
        ),
    ]
