# Generated by Django 4.2.25 on 2026-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_legacy_college_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code (e.g., CS, ENG)', max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('head_name', models.CharField(blank=True, help_text='Department head name', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is department currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_depart_name_80d4fe_idx'), models.Index(fields=['code'], name='core_depart_code_5a5745_idx')],
            },
        ),
    ]
