# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', help_text="Teacher's photograph"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, null=True, unique=True, max_length=254, help_text="Teacher's email address"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, null=True, max_length=15, help_text="Teacher's phone number"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, help_text="Teacher's date of birth"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=10,
                choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')],
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True, help_text='Home address'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, null=True, max_length=100, help_text='Department/Faculty'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, null=True, max_length=200, help_text='Highest qualification'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, null=True, max_length=200, help_text='Area of specialization'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, help_text='Date of employment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(
                max_length=20,
                default='full_time',
                choices=[
                    ('full_time', 'Full Time'),
                    ('part_time', 'Part Time'),
                    ('contract', 'Contract'),
                    ('visiting', 'Visiting'),
                    ('adjunct', 'Adjunct'),
                ],
                help_text='Employment status',
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_courses',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of courses per session'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Currently employed'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
