# Generated by Django 4.2.25 on 2026-01-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_add_profile_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['staff_id'], name='teachers_te_staff_i_918799_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teachers_te_departm_3b845d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employment_type', 'is_active'], name='teachers_te_employm_c4d29b_idx'),
        ),
    ]
