# Generated by Django 4.2.25 on 2026-01-08 16:09

from django.db import migrations, models
import django.db.models.deletion


def copy_department_to_name(apps, schema_editor):
    """Copy existing department text values to department_name before converting to FK"""
    Teacher = apps.get_model('teachers', 'Teacher')
    for teacher in Teacher.objects.all():
        if teacher.department:
            teacher.department_name = teacher.department
            teacher.save(update_fields=['department_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_department_model'),
        ('teachers', '0003_teacher_teachers_te_staff_i_918799_idx_and_more'),
    ]

    operations = [
        # Step 1: Add the new department_name field
        migrations.AddField(
            model_name='teacher',
            name='department_name',
            field=models.CharField(blank=True, help_text='Department name (legacy)', max_length=100, null=True),
        ),
        # Step 2: Copy existing department values to department_name
        migrations.RunPython(copy_department_to_name, migrations.RunPython.noop),
        # Step 3: Remove the old index
        migrations.RemoveIndex(
            model_name='teacher',
            name='teachers_te_departm_3b845d_idx',
        ),
        # Step 4: Remove the old department CharField
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        # Step 5: Add the new department ForeignKey
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department/Faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.department'),
        ),
        # Step 6: Add new index for the FK
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teachers_te_departm_e41848_idx'),
        ),
    ]
