# Generated by Django 4.2.25 on 2026-01-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=32, unique=True, db_index=True)),
                ('student_name', models.CharField(max_length=255)),
                ('generation_timestamp', models.DateTimeField()),
                ('document_hash', models.CharField(max_length=64)),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('verification_url', models.URLField(blank=True)),
                ('payload_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True, db_index=True)),
                ('revoked_at', models.DateTimeField(null=True, blank=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_verifications', to='students.student')),
            ],
        ),
    ]
