# Generated by Django 4.2.25 on 2025-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
