# Generated by Django 4.2.25 on 2026-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_semester',
            field=models.CharField(blank=True, choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], max_length=6, null=True),
        ),
    ]
