# Generated by Django 4.2.25 on 2026-01-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_department_model'),
        ('courses', '0004_courseoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department offering this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.department'),
        ),
    ]
