# Generated by Django 4.2.25 on 2026-01-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_add_department_fk'),
        ('courses', '0005_add_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned to teach this offering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['session', 'semester'], name='courses_cou_session_204246_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'session'], name='courses_cou_course__2ae9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['teacher'], name='courses_cou_teacher_f84e39_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_1ed7ce_idx'),
        ),
    ]
