# Generated by Django 4.2.25 on 2025-10-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('grading', '0003_alter_enrollment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.session'),
        ),
    ]
