# Generated by Django 4.2.25 on 2025-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_enrollment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsettings',
            name='grade_point',
            field=models.FloatField(default=0.0),
        ),
    ]
