# Generated by Django 4.2.25 on 2026-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_units'),
        ('students', '0004_alter_student_options_and_more'),
        ('grading', '0005_gradingsettings_grade_point'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], default='FIRST', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'session', 'semester')},
        ),
    ]
