# Generated by Django 4.2.25 on 2026-01-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_add_semester_to_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer')], default='FIRST', max_length=6),
        ),
    ]
