# Generated by Django 4.2.25 on 2026-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_grade_approval_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingsettings',
            options={'ordering': ['-min_score']},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='grading_enr_student_628c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_offering'], name='grading_enr_course__db821e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='grading_enr_enrollm_3e8b90_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course_offering'], name='grading_enr_student_2f77d8_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['status'], name='grading_gra_status_61e56c_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade'], name='grading_gra_grade_32dd49_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['total_score'], name='grading_gra_total_s_dd5d58_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['submitted_at'], name='grading_gra_submitt_b22a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['approved_at'], name='grading_gra_approve_0dce67_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingsettings',
            index=models.Index(fields=['min_score'], name='grading_gra_min_sco_f16fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingsettings',
            index=models.Index(fields=['grade_name'], name='grading_gra_grade_n_fe2375_idx'),
        ),
    ]
