# Generated by Django 4.2.25 on 2026-01-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='min_units_to_graduate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
